### ISSUE TITLE
Team 12 VnV Report Review - Lack of Input and Output states for unit tests

### ISSUE THREAD

**Issue by Umang-Rajkarnikar** [tusharagg1/chest-x-ray-ai#115]
Hey, solid VnV Report! One thing I noticed was that in your unit tests (Section 5), the tests for the methods of each module do not include input and output states. I feel that including them can possibly provide more insight when conducting an evaluation of each software module.

This issue was created by Team 12 as part of VnV Report Review. Tagging marking TA as recommended @samm82

[Review-Team12]

**Comment by AllisonRCook** [comment]
Completed as part of the final document update
