### ISSUE TITLE
Team 12 VnV Report Review - Section 6 Changes due to testing

### ISSUE THREAD

**Issue by Umang-Rajkarnikar** [tusharagg1/chest-x-ray-ai#116]
In section 6 (Changes due to Testing), the changes detailed do not reference the affected functional or nonfunctional requirements. I feel that by adding this information it improves traceability across the development, and verification and validation processes.

This issue was created by Team 12 as part of VnV Report Review. Tagging marking TA as recommended @samm82

[Review-Team12]

**Comment by AllisonRCook** [comment]
The VnV report has been updated to reflect the changes made to requirements based on the changes made due to testing. Changes are reflected in the final documentation commit
