### ISSUE TITLE
Haz Analysis [Final Doc]

### ISSUE THREAD

**Issue by tusharagg1** [tusharagg1/chest-x-ray-ai#135]
> ## Feedback from Avenue
> Please update the concerned documents based on the feedback from the Professor and TA on Avenue.
> **Important:** _Also, update the document with the latest information based on our Final Demo/Product._
> 
> ### Haz Analysis
> - [x] Hazard analysis revised and improved - @Ibrahimango02 
> - [x] Inconsistent format - @
> - [x] unclear in "The system is assumed to be available for use at all times, with minimal downtime." Too strict in the assumption - @mohaanshpranjal 
> - [x] Causes of Failure could add more key points - @mohaanshpranjal 
> - [x] An excellent job has been doing addressing the feedback from the Tas, instructor, supervisor (when present), teammates,  other teams, and test users.  The feedback has been conscientiously, completely and consistently addressed.  The changes are clearly and completely documented. Traceability between the HA and SRS is clear.
> - [x] Traceability between all documents (Hazards to reqs, reqs to hazards, reqs to modules, etc.)
> - [x] Update major revisions table.
> - [x] Check the **Important** note above - @mohaanshpranjal 
> - [x] Refer to the rubric - @mohaanshpranjal 
> - [x] Reviewed by @Ibrahimango02 

 _Originally posted by @tusharagg1 in [#130](https://github.com/tusharagg1/chest-x-ray-ai/issues/130#issuecomment-2019519629)_

**Comment by mohaanshpranjal** [comment]
Updated critical assumptions
Added causes of failure in FMEA table and removed data collection (commented for retrievability)
Removed image upload case by user from FMEA table

Not sure what is meant by  _"Inconsistent format"_. Pls review.

**Comment by tusharagg1** [comment]
@Ibrahimango02 did you review the issue with the format?
` Inconsistent format`
I don't see the item checked above.
