### ISSUE TITLE
VnV Plan [Final Doc]

### ISSUE THREAD

**Issue by tusharagg1** [tusharagg1/chest-x-ray-ai#136]
> ## Feedback from Avenue
> Please update the concerned documents based on the feedback from the Professor and TA on Avenue.
> **Important:** _Also, update the document with the latest information based on our Final Demo/Product._
> 
> ### VnV Plan
> - [x] VnV Plan revised (complete unit testing sections) - @AllisonRCook 
>   - [x] Summarize unit testing philosophy  -@AllisonRCook 
>   - [x] Point to unit testing code - @AllisonRCook 
> - [ ] Change the paper number to be consistent - see [this comment](https://github.com/tusharagg1/chest-x-ray-ai/issues/136#issuecomment-2038698187)
> - [x] Using test-id for all test, should be changed - @AllisonRCook 
> - [x] Missing static test - @AllisonRCook 
> - [x] An excellent job has been doing addressing the feedback from the Tas, instructor, supervisor (when present), teammates,  other teams, and test users.  The feedback has been conscientiously, completely and consistently addressed.  Unit test summary added to VnV plan. The changes are clearly and completely documented.
> - [x] Update major revisions table.
> - [x] Check the **Important** note above - @AllisonRCook 
> - [x] Refer to the rubric - @AllisonRCook 
> - [x] Reviewed by @Nathaniel-Hu 

 _Originally posted by @tusharagg1 in [#130](https://github.com/tusharagg1/chest-x-ray-ai/issues/130#issuecomment-2019519629)_

**Comment by tusharagg1** [comment]
@Ibrahimango02 @Nathaniel-Hu 
Add features from below:
https://github.com/tusharagg1/chest-x-ray-ai/settings/security_analysis

**Comment by AllisonRCook** [comment]
Unsure what "consistent page numbers" need to change as all values are present and consistent with the other existing documents
