### ISSUE TITLE
Design Doc [Final Doc]

### ISSUE THREAD

**Issue by tusharagg1** [tusharagg1/chest-x-ray-ai#137]
> ## Feedback from Avenue
> Please update the concerned documents based on the feedback from the Professor and TA on Avenue.
> **Important:** _Also, update the document with the latest information based on our Final Demo/Product._
> 
> ### Design Doc
> - [x] Design Document revised and improved - @
> - [x] missing variables - @
> - [x] only one review - @
> - [x] An excellent job has been doing addressing the feedback from the Tas, instructor, supervisor (when present), teammates,  other teams, and test users.  The feedback has been conscientiously, completely and consistently addressed.  The changes are clearly and completely documented.
> - [x] Update major revisions table.
> - [x] Check the **Important** note above - @
> - [x] Refer to the rubric - @
> - [x] Reviewed by @Ibrahimango02 

 _Originally posted by @tusharagg1 in [#130](https://github.com/tusharagg1/chest-x-ray-ai/issues/130#issuecomment-2019519629)_

**Comment by mohaanshpranjal** [comment]
MG: Updated modules regarding ML model according to the implementation, and subsequent changes in traceability

MIS: updated MIS for backend ML modules according to changes during implementation

SystDes:
