### ISSUE TITLE
VnV Report [Final Doc]

### ISSUE THREAD

**Issue by tusharagg1** [tusharagg1/chest-x-ray-ai#138]
> ## Feedback from Avenue
> Please update the concerned documents based on the feedback from the Professor and TA on Avenue.
> **Important:** _Also, update the document with the latest information based on our Final Demo/Product._
> 
> ### VnV Report
> - [x] VnV Report revised and improved - @Ibrahimango02 
> - [x] An excellent job has been doing addressing the feedback from the Tas, instructor, supervisor (when present), teammates,  other teams, and test users.  The feedback has been conscientiously, completely and consistently addressed.  Unit test summary added to VnV plan. The changes are clearly and completely documented.
> - [x] Update major revisions table - @Ibrahimango02 
> - [x] Check the **Important** note above - @Ibrahimango02 
> - [x] Refer to the rubric - @Ibrahimango02 
> - [x] Reviewed by @AllisonRCook 

 _Originally posted by @tusharagg1 in [#130](https://github.com/tusharagg1/chest-x-ray-ai/issues/130#issuecomment-2019519629)_

**Comment by Ibrahimango02** [comment]
VnV report was revised and improved to match final demo. Waiting for mohaansh and nathaniel to fix output states for unit tests.
