### ISSUE TITLE
Write SRS, Rev0

### ISSUE THREAD

**Issue by tusharagg1** [tusharagg1/chest-x-ray-ai#15]
## Summary
- Write SRS Rev0

## Deadline
- 10/06/2023

## Estimated Work Time (in hrs)
- 6 hrs

**Comment by Tusharagg1** [comment]
### Related commits:
- [feat: SRS-Volere Deliverable, Revision 0](https://github.com/Tusharagg1/chest-x-ray-ai/commit/d29f582a56a23504392d894301f848f783caeca8)
- [Updated \authname and \progname commands with proper information for …](https://github.com/Tusharagg1/chest-x-ray-ai/commit/5bf1f6cd3022b1a202fbf64c6b58d2697d37ba02)

**Comment by Tusharagg1** [comment]
### New commits:
- [feat: updated SRS with more sections filled in](https://github.com/Tusharagg1/chest-x-ray-ai/commit/39b7fadff703726e816ad5682ec36fb88c1bce9f)
- [feat: updates to SRS documentation](https://github.com/Tusharagg1/chest-x-ray-ai/commit/2f8aa174d2bc85d7f3bc0212cb37df2583aacb22)
