### ISSUE TITLE
Verify Source Code Quality [Final Doc]

### ISSUE THREAD

**Issue by tusharagg1** [tusharagg1/chest-x-ray-ai#151]
> ## Final Doc slides
> 
> ### Source Code Quality
> - [ ] Explicit identification of coding standards
> - [ ] Comments for what not how
> - [ ] Identifiers that are consistent, distinctive, and meaningful
> - [ ] Avoidance of hard-coded constants (other than 0 or 1)
> - [ ] Appropriate modularization
> - [ ] Consistent indentation
> - [ ] Parameters are in the same order for all functions
> - [ ] Descriptive names of source code files
> - [ ] Clear mapping between code and design modules 
> - [ ] Code formatting and style are excellent. The code has good comments (explain what, but not how; code identifies its author, date, purpose), avoids hard-coded constants (uses symbolic constants), avoids 0 and 1 for False and True (unless language requires this), uses enumerated types rather than having to remember special integer codes.  A coding standard is consistently used for naming variables, naming functions, naming classes, indentation, etc. Mapping between the Code and the module documentation is clear.
> - [x] Refer to the rubric - @mohaanshpranjal @AllisonRCook 
> - [ ] Reviewed by @Nathaniel-Hu 

 _Originally posted by @tusharagg1 in [#130](https://github.com/tusharagg1/chest-x-ray-ai/issues/130#issuecomment-2019539310)_

**Comment by mohaanshpranjal** [comment]
> ### Source Code Quality for backend ML model code (@mohaanshpranjal)
> - [ ] Explicit identification of coding standards
> - [ ] Comments for what not how
> - [ ] Identifiers that are consistent, distinctive, and meaningful
> - [ ] Avoidance of hard-coded constants (other than 0 or 1)
> - [ ] Appropriate modularization
> - [ ] Consistent indentation
> - [ ] Parameters are in the same order for all functions
> - [ ] Descriptive names of source code files
> - [ ] Clear mapping between code and design modules 
> - [ ] Code formatting and style are excellent. The code has good comments (explain what, but not how; code identifies its author, date, purpose), avoids hard-coded constants (uses symbolic constants), avoids 0 and 1 for False and True (unless language requires this), uses enumerated types rather than having to remember special integer codes.  A coding standard is consistently used for naming variables, naming functions, naming classes, indentation, etc. Mapping between the Code and the module documentation is clear.

**Comment by AllisonRCook** [comment]
> ### Source Code Quality for Frontend Code
> - [ ] Explicit identification of coding standards
> - [ ] Comments for what not how
> - [ ] Identifiers that are consistent, distinctive, and meaningful
> - [ ] Avoidance of hard-coded constants (other than 0 or 1)
> - [ ] Appropriate modularization
> - [ ] Consistent indentation
> - [ ] Parameters are in the same order for all functions
> - [ ] Descriptive names of source code files
> - [ ] Clear mapping between code and design modules 
> - [ ] Code formatting and style are excellent. The code has good comments (explain what, but not how; code identifies its author, date, purpose), avoids hard-coded constants (uses symbolic constants), avoids 0 and 1 for False and True (unless language requires this), uses enumerated types rather than having to remember special integer codes.  A coding standard is consistently used for naming variables, naming functions, naming classes, indentation, etc. Mapping between the Code and the module documentation is clear.
> - [ ] Refer to the rubric - @
> - [ ] Reviewed by @{other team member}

**Comment by tusharagg1** [comment]
@Nathaniel-Hu as per above, did you finish reviewing it?
