### ISSUE TITLE
Create Video [Capstone EXPO]

### ISSUE THREAD

**Issue by tusharagg1** [tusharagg1/chest-x-ray-ai#155]
### Rubric
- Promotes project and accomplishments
  - [ ] After watching the video the viewer is left with an impression that the team accomplished something truly noteworthy - something that a team of 4 to 5 senior software students would need to work on for 8 months
- Production value
  - [ ] Video and sound quality are excellent.

> ### Video Advice
> - Sample video of [piano performance pal](https://www.youtube.com/watch?v=e_6C_emnDws)
> - Video length of 4 to 6 minutes
> - Public (ideally) or private link to video on YouTube
> [- Beginner’s guide to using your phone for videos](https://mcmasteru365.sharepoint.com/sites/Capstone2023-TeamLeadChannel/_layouts/15/AccessDenied.aspx?Source=https%3A%2F%2Fmcmasteru365%2Esharepoint%2Ecom%2Fsites%2FCapstone2023%2DTeamLeadChannel%2FClass%20Materials%2FForms%2FAllItems%2Easpx%3Fid%3D%252Fsites%252FCapstone2023%252DTeamLeadChannel%252FClass%2520Materials%252FBeginner%2527s%2520Phone%2520Video%2520Recording%2520Guide%252Epdf%26parent%3D%252Fsites%252FCapstone2023%252DTeamLeadChannel%252FClass%2520Materials&correlation=41e919a1%2D1098%2D5000%2D17c6%2Db76e56c2adb9&Type=item&name=d3a2a4e1%2Dab1d%2D4a37%2Da463%2D31fb061c5966&listItemId=1&listItemUniqueId=dae54ebd%2Df1e8%2D4f5c%2Dac02%2D417344e94ac6)
> - You could record your presentation using Teams 

 _Originally posted by @tusharagg1 in [#153](https://github.com/tusharagg1/chest-x-ray-ai/issues/153#issuecomment-2027802507)_

**Comment by mohaanshpranjal** [comment]
youtube link:
https://youtu.be/DrO5Eo3eGmM
