### ISSUE TITLE
Team 12 SRS Review - No Reflection 

### ISSUE THREAD

**Issue by DiamondAhuja** [Tusharagg1/chest-x-ray-ai#21]
The reflection section in your SRS document is missing. It is important to add reflection to the document as it is used to evaluate team members on attribute of lifelong learning. It focuses on what the team needs to work on collectively, the skills and knowledge they need to gather if they don't currently have them. Additionally, it helps in gaining insight on what team members' interests are. They also need to list ways in which they are planning to acquire those skills and their reasoning behind it.

This issue was created by Team 12 as part of SRS Primary Review. Tagging marking TA as recommended @samm82

[Review-Team12]

**Comment by Tusharagg1** [comment]
@Ibrahimango02 I think you mentioned doing the reflection. Is it complete and can the issue be closed?
