### ISSUE TITLE
Team 12 SRS Review - Functional Requirement Rationale

### ISSUE THREAD

**Issue by Umang-Rajkarnikar** [Tusharagg1/chest-x-ray-ai#22]
Many of the functional requirements listed in the SRS document do not state a rationale. It is unclear on the justification of the several requirements listed in the document. Rationales are important since they help explain why certain requirements are needed, both prior to and during the development phases. Moreover, it also helps stakeholders and developers understand the need for it. Including rationales to your functional requirements can strengthen the understanding and need of our product.

This issue was created by Team 12 as part of SRS Primary Review. Tagging marking TA as recommended @samm82

[Review-Team12]

**Comment by Tusharagg1** [comment]
@mohaanshpranjal please add comments.
_(I am aiming to automate this rule for future issues)_

**Comment by mohaanshpranjal** [comment]
added rationale to functional requirements.
