### ISSUE TITLE
Team 12 SRS Review - Functional Requirements Criterion Missing

### ISSUE THREAD

**Issue by Umang-Rajkarnikar** [Tusharagg1/chest-x-ray-ai#23]
Many of the functional requirements in the SRS document are missing a criterion to measure the verifiability and completeness of the requirements. A criterion is useful when evaluating the achievability of a requirement and testing if it has been satisfied. Adding the criterions to your SRS document will provide a traceable way to assess the requirements of your product.

This issue was created by Team 12 as part of SRS Primary Review. Tagging marking TA as recommended @samm82

[Review-Team12]

**Comment by mohaanshpranjal** [comment]
completed mapping PUCs an adding fir criterion in section 2.4.
