### ISSUE TITLE
Team 12 SRS Review - Incomplete Constraints 

### ISSUE THREAD

**Issue by dhruvcheemakurti** [Tusharagg1/chest-x-ray-ai#24]
Constraints:

The Constraints section in the SRS document is incomplete. Regarding the solution constraints, there was an incomplete rationale and fit criterion. Neither was there an explanation on the implementation environment of the current system as there were empty bullet points. Same applies to the off-the-shell software. There was reasonable explanation about the anticipated workplace environment, schedule and enterprise constraints. It is important for the SRS document to outline the reason and rationale for the constraints as it helps understand the scope of the project. Without constraints, it is hard to judge if a project can even be done which is important for any stakeholder to know. With respect to the rubric, it would be a level 1 because only a few sections provide some constraints, while the others are missing and without appropriate rationale.  

This issue was created by Team 12 as part of SRS Primary Review. Tagging marking TA as recommended [@samm82](https://github.com/samm82)

[Review-Team12]

**Comment by Tusharagg1** [comment]
@Nathaniel-Hu Is it complete and can the issue be closed now?
