### ISSUE TITLE
Team 12 SRS Review - Missing Tasks and Project Planning

### ISSUE THREAD

**Issue by DiamondAhuja** [Tusharagg1/chest-x-ray-ai#25]
The SRS document was missing a very important section, Tasks (Section 21). This section includes project planning and the planning of the development phases. It is important to state priority requirements and the specific timeline for when they will be implemented in the project. There are many milestones for this project that each team needs to complete, along with coding for the actual project. Therefore, having a timeline plan for the tasks needed to be done is very crucial.

This issue was created by Team 12 as part of SRS Primary Review. Tagging marking TA as recommended @samm82

[Review-Team12]

**Comment by Tusharagg1** [comment]
Completed "Tasks (Section 21)" for SRS.
