### ISSUE TITLE
Team 12 HA Review - Addition to Causes of Failure

### ISSUE THREAD

**Issue by DiamondAhuja** [tusharagg1/chest-x-ray-ai#32]
I would start by saying that the components and failure modes are well thought out and suitable for your project. It would be great to add more information/points on the causes of failure section. 
For example: 

- Failure mode: Fails to upload chest x-ray image
- Causes of failure could be:
  - File size too large
  - image is an unsupported format
  - unstable internet connection

This issue was created by Team 12 as part of SRS Primary Review. Tagging marking TA as recommended @samm82

[Review-Team12]

**Comment by mohaanshpranjal** [comment]
Updated critical assumptions; added causes of failure in FMEA table and removed data collection (commented for retrievability)
