### ISSUE TITLE
Team 12 HA Review - Missing Safety/Security Requirements

### ISSUE THREAD

**Issue by Umang-Rajkarnikar** [Tusharagg1/chest-x-ray-ai#37]
The hazards listed for the backend server component do not map to a safety or security requirement(s). The hazards listed were network failure and server downtime, which are problems that can occur during the build and production of a software application.

Perhaps, an accessibility requirement can be added to evaluate server availability and network balancing. 

This issue was created by Team 12 as part of Hazard Analysis Review. Tagging marking TA as recommended @samm82

[Review-Team12]

**Comment by Tusharagg1** [comment]
Team to map 'FMEA' to 'Safety and Security Requirements' - All of them should be linked.
