### ISSUE TITLE
Team 12 VnV Plan Review - Traceability table incorrect test ids

### ISSUE THREAD

**Issue by DiamondAhuja** [tusharagg1/chest-x-ray-ai#56]
The traceability table in your VnV Plan does not match with the test cases you have for functional and non-functional requirements. I am assuming the numbering is still correct but the name should be testid instead of T. It should be a quick fix. Other than that, great work!

This issue was created by Team 12 as part of Hazard analysis Primary Review. Tagging marking TA as recommended @samm82

[Review-Team12]

**Comment by AllisonRCook** [comment]
Included number change, along with the avenue number change
