### ISSUE TITLE
Team 12 VnV Plan Review - 3.1 Verification and Validation Team

### ISSUE THREAD

**Issue by Umang-Rajkarnikar** [tusharagg1/chest-x-ray-ai#58]
In the section 3.1 Verification and Validation Team, many team members share the same role/responsibilities. Since there are several verification tasks such as SRS verification, design verification, and code verification, perhaps team members could be assigned in such a way where there is a clear plan to implement each of these verification tasks.

This issue was created by Team 12 as part of VnV Plan Review. Tagging marking TA as recommended @samm82

[Review-Team12]

**Comment by AllisonRCook** [comment]
Added focus points in code and documentation for VnV
