### ISSUE TITLE
Create PR Check workflow

### ISSUE THREAD

**Issue by tusharagg1** [tusharagg1/chest-x-ray-ai#8]
## Summary
- Create a PR check workflow

## Deadline
- 09/22/2023

## Estimated Work Time (in hrs)
- 1 hrs

### Related commits: 
- [Create PR check workflow](https://github.com/Tusharagg1/chest-x-ray-ai/commit/10e5e1a31533aa347f3c9dc70594ade8fc401388)

**Comment by Tusharagg1** [comment]
## Summary
- First PR was performed.
- Testing was a success.

**Linked Issue**: #40

**Comment by tusharagg1** [comment]
## Summary
- Created other PR workflows (GitHub Actions)
-- Create Branch from Issue
-- 
- Improvised PR check workflow


## Estimated Work Time (in hrs)
- 12 hrs


### Related commits: 
-

**Comment by tusharagg1** [comment]
## Summary
- Improvised PR check workflow


### Related issues:
- #9
