### ISSUE TITLE
Team Name to TeamComposition.csv

### ISSUE THREAD

**Issue by smiths** [tusharagg1/chest-x-ray-ai#86]
Please create a pull request to add a team name to `TeamComposition.csv` in the course repo.

**Comment by tusharagg1** [comment]
Added Team Name.

https://gitlab.cas.mcmaster.ca/courses/capstone/-/merge_requests/194
Merge Request Reference: courses/capstone!194
Commit ID: ce824f0c532802b308d28e9aa8792e2784a40aa1

**Comment by smiths** [comment]
I've accepted the merge request.

**Comment by tusharagg1** [comment]
### Related documentation:
https://forms.office.com/Pages/DesignPageV2.aspx?subpage=design&id=B2M3RCm0rUKMJSjNSW9Hctrjy36IXgJClK5DPlMQ_adUMFlUMVpRRktRWENEWTVKR0lIWElCVUg1NC4u&analysis=true&origin=TeamsBot&tab=0
