### ISSUE TITLE
Backend Modules - Implementations

### ISSUE THREAD

**Issue by Nathaniel-Hu** [tusharagg1/chest-x-ray-ai#96]
## Summary
The following Backend modules are to be implemented:
- Backend
- UserAuthMgmt
- DatabaseOps
- MedInstInter

## Deadline
- TBD

## Estimated Work Time (in hrs)
- TDB

**Comment by tusharagg1** [comment]
@Nathaniel-Hu can you update the progress and perform actions as required?
